services:
  catalogo-api:
    image: catalogo-api
    build: .
    command: uvicorn main.asgi:application --reload --host=0.0.0.0
    env_file:
      - .env
    ports:
      - 8000:8000
    develop:
      # Create a `watch` configuration to update the app
      #
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: .
          target: /app
          # Exclude the project virtual environment
          ignore:
            - .venv/

        # Rebuild the image on changes to the `pyproject.toml`
        - action: rebuild
          path: ./pyproject.toml